### ISSUE TITLE
Suggestion: use lodash clone

### ISSUE THREAD

**Issue by morenoh149** [emertechie/express-local-auth#2]
I noticed you use two separate clone functions to make object copies.
https://github.com/emertechie/express-local-auth/blob/e34bd21956287a4dc472739145569c4409739eb3/tests/fakes/userStore.js#L58
https://github.com/emertechie/express-local-auth/blob/e34bd21956287a4dc472739145569c4409739eb3/tests/fakes/tokenStore.js#L29
Since you already have lodash as a dependency you could remove these by using [clone](https://lodash.com/docs#clone) or cloneDeep

**Comment by emertechie** [comment]
good spot. cheers
